Add files via upload

diff --git a/other/server_status_server_centos b/other/server_status_server_centos
--- a/other/server_status_server_centos
+++ b/other/server_status_server_centos
@@ -30,8 +30,13 @@ check_running(){
 	fi
 }
 Read_config(){
-	[[ ! -e "${CONF1}" ]] && echo -e "${Error} ServerStatus 服务端配置文件不存在 !" && exit 1
-	port="$(cat "${CONF1}"|grep "PORT = "|awk '{print $3}')"
+	if [[ ! -e "${CONF1}" ]]; then
+		port="--port=$(cat "${CONF1}"|grep "PORT = "|awk '{print $3}')"
+		port="--port=${port}"
+	else
+		port=""
+		echo -e "${Error} ServerStatus 服务端配置文件不存在 !" && exit 1
+	if
 }
 do_start(){
 	check_running
@@ -40,7 +45,7 @@ do_start(){
 	else
 		Read_config
 		cd "${SERVER_BIN}"
-		nohup "./$NAME_BIN" --config="$CONF" --web-dir="$WEB_BIN" --port=${port} > /tmp/serverstatus_server.log 2>&1 &
+		nohup "./$NAME_BIN" --config="$CONF" --web-dir="$WEB_BIN" "${port}" > /tmp/serverstatus_server.log 2>&1 &
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
diff --git a/other/server_status_server_debian b/other/server_status_server_debian
--- a/other/server_status_server_debian
+++ b/other/server_status_server_debian
@@ -28,8 +28,13 @@ check_running(){
 	fi
 }
 Read_config(){
-	[[ ! -e "${CONF1}" ]] && echo -e "ServerStatus 服务端配置文件不存在 !" && exit 1
-	port="$(cat "${CONF1}"|grep "PORT = "|awk '{print $3}')"
+	if [[ ! -e "${CONF1}" ]]; then
+		port="--port=$(cat "${CONF1}"|grep "PORT = "|awk '{print $3}')"
+		port="--port=${port}"
+	else
+		port=""
+		echo -e "${Error} ServerStatus 服务端配置文件不存在 !" && exit 1
+	if
 }
 do_start(){
 	check_running
